// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/authentication": {
            "post": {
                "description": "Authenticate user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "description": "User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User with token",
                        "schema": {
                            "$ref": "#/definitions/UserDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/experience": {
            "get": {
                "description": "Gets experiences",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experience"
                ],
                "summary": "Get experiences",
                "responses": {
                    "200": {
                        "description": "Experiences",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ExperienceDto"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "description": "Updates experience",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experience"
                ],
                "summary": "Update experiences",
                "parameters": [
                    {
                        "description": "Experience",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ExperienceDto"
                        }
                    },
                    {
                        "type": "string",
                        "description": "BasicAuth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated experience",
                        "schema": {
                            "$ref": "#/definitions/ExperienceDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Creates experience",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experience"
                ],
                "summary": "Create experience",
                "parameters": [
                    {
                        "description": "Experience",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UserDto"
                        }
                    },
                    {
                        "type": "string",
                        "description": "BasicAuth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created experience",
                        "schema": {
                            "$ref": "#/definitions/ExperienceDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Deletes experience",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "experience"
                ],
                "summary": "Delete experiences",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Experience id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "BasicAuth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "$ref": "#/definitions/ResponseDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/technology": {
            "get": {
                "description": "Gets technologies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "technology"
                ],
                "summary": "Get technologies",
                "responses": {
                    "200": {
                        "description": "Technologies",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/TechnologyDto"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "description": "Updates technologies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "technology"
                ],
                "summary": "Update technology",
                "parameters": [
                    {
                        "description": "Technology",
                        "name": "technology",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/TechnologyDto"
                        }
                    },
                    {
                        "type": "string",
                        "description": "BasicAuth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated technology",
                        "schema": {
                            "$ref": "#/definitions/TechnologyDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Creates technologies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "technology"
                ],
                "summary": "Create technology",
                "parameters": [
                    {
                        "description": "Technology",
                        "name": "technology",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/TechnologyDto"
                        }
                    },
                    {
                        "type": "string",
                        "description": "BasicAuth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created technology",
                        "schema": {
                            "$ref": "#/definitions/TechnologyDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Deletes technology",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "technology"
                ],
                "summary": "Delete technology",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Technology id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "BasicAuth token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "$ref": "#/definitions/ResponseDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/telemetry": {
            "get": {
                "description": "Gets telemetries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Get telemetries",
                "responses": {
                    "200": {
                        "description": "Telemetries",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/TelemetryDto"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Creates telemetry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "summary": "Create telemetry",
                "parameters": [
                    {
                        "description": "Telemetry",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/TelemetryDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created telemetry",
                        "schema": {
                            "$ref": "#/definitions/ExperienceDto"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "ExperienceDto": {
            "type": "object",
            "properties": {
                "company": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "responsibilities": {
                    "type": "string"
                },
                "timeFrame": {
                    "type": "string"
                }
            }
        },
        "ResponseDto": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "TechnologyDto": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "experience": {
                    "type": "string"
                },
                "logoClass": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "TelemetryDto": {
            "type": "object",
            "properties": {
                "countryIso": {
                    "type": "string"
                },
                "countryName": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "UserDto": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
