// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { PostApiAuthenticationData, PostApiAuthenticationResponse, DeleteApiExperienceData, DeleteApiExperienceResponse, GetApiExperienceData, GetApiExperienceResponse, PostApiExperienceData, PostApiExperienceResponse, PutApiExperienceData, PutApiExperienceResponse, DeleteApiTechnologyData, DeleteApiTechnologyResponse, GetApiTechnologyData, GetApiTechnologyResponse, PostApiTechnologyData, PostApiTechnologyResponse, PutApiTechnologyData, PutApiTechnologyResponse, GetApiTelemetryData, GetApiTelemetryResponse, PostApiTelemetryData, PostApiTelemetryResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Authenticate user
 * Authenticate user
 */
export const postApiAuthentication = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthenticationData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiAuthenticationResponse, unknown, ThrowOnError>({
        url: '/api/authentication',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete experiences
 * Deletes experience
 */
export const deleteApiExperience = <ThrowOnError extends boolean = false>(options: Options<DeleteApiExperienceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteApiExperienceResponse, unknown, ThrowOnError>({
        url: '/api/experience',
        ...options
    });
};

/**
 * Get experiences
 * Gets experiences
 */
export const getApiExperience = <ThrowOnError extends boolean = false>(options?: Options<GetApiExperienceData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiExperienceResponse, unknown, ThrowOnError>({
        url: '/api/experience',
        ...options
    });
};

/**
 * Create experience
 * Creates experience
 */
export const postApiExperience = <ThrowOnError extends boolean = false>(options: Options<PostApiExperienceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiExperienceResponse, unknown, ThrowOnError>({
        url: '/api/experience',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Update experiences
 * Updates experience
 */
export const putApiExperience = <ThrowOnError extends boolean = false>(options: Options<PutApiExperienceData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutApiExperienceResponse, unknown, ThrowOnError>({
        url: '/api/experience',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Delete technology
 * Deletes technology
 */
export const deleteApiTechnology = <ThrowOnError extends boolean = false>(options: Options<DeleteApiTechnologyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteApiTechnologyResponse, unknown, ThrowOnError>({
        url: '/api/technology',
        ...options
    });
};

/**
 * Get technologies
 * Gets technologies
 */
export const getApiTechnology = <ThrowOnError extends boolean = false>(options?: Options<GetApiTechnologyData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiTechnologyResponse, unknown, ThrowOnError>({
        url: '/api/technology',
        ...options
    });
};

/**
 * Create technology
 * Creates technologies
 */
export const postApiTechnology = <ThrowOnError extends boolean = false>(options: Options<PostApiTechnologyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiTechnologyResponse, unknown, ThrowOnError>({
        url: '/api/technology',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Update technology
 * Updates technologies
 */
export const putApiTechnology = <ThrowOnError extends boolean = false>(options: Options<PutApiTechnologyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutApiTechnologyResponse, unknown, ThrowOnError>({
        url: '/api/technology',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get telemetries
 * Gets telemetries
 */
export const getApiTelemetry = <ThrowOnError extends boolean = false>(options?: Options<GetApiTelemetryData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiTelemetryResponse, unknown, ThrowOnError>({
        url: '/api/telemetry',
        ...options
    });
};

/**
 * Create telemetry
 * Creates telemetry
 */
export const postApiTelemetry = <ThrowOnError extends boolean = false>(options: Options<PostApiTelemetryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiTelemetryResponse, unknown, ThrowOnError>({
        url: '/api/telemetry',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};