// This file is auto-generated by @hey-api/openapi-ts

export type ExperienceDto = {
    company?: string;
    position?: string;
    responsibilities?: string;
    timeFrame?: string;
};

export type ResponseDto = {
    message?: string;
};

export type TechnologyDto = {
    description?: string;
    experience?: string;
    logoClass?: string;
    name?: string;
};

export type TelemetryDto = {
    countryIso?: string;
    countryName?: string;
    timestamp?: string;
};

export type UserDto = {
    password?: string;
    token?: string;
    username?: string;
};

export type PostApiAuthenticationData = {
    /**
     * User
     */
    body: UserDto;
    path?: never;
    query?: never;
    url: '/api/authentication';
};

export type PostApiAuthenticationErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostApiAuthenticationResponses = {
    /**
     * User with token
     */
    201: UserDto;
};

export type PostApiAuthenticationResponse = PostApiAuthenticationResponses[keyof PostApiAuthenticationResponses];

export type DeleteApiExperienceData = {
    body?: never;
    headers: {
        /**
         * BasicAuth token
         */
        Authorization: string;
    };
    path: {
        /**
         * Experience id
         */
        id: number;
    };
    query?: never;
    url: '/api/experience';
};

export type DeleteApiExperienceErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type DeleteApiExperienceResponses = {
    /**
     * Success message
     */
    200: ResponseDto;
};

export type DeleteApiExperienceResponse = DeleteApiExperienceResponses[keyof DeleteApiExperienceResponses];

export type GetApiExperienceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/experience';
};

export type GetApiExperienceErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetApiExperienceResponses = {
    /**
     * Experiences
     */
    200: Array<ExperienceDto>;
};

export type GetApiExperienceResponse = GetApiExperienceResponses[keyof GetApiExperienceResponses];

export type PostApiExperienceData = {
    /**
     * Experience
     */
    body: UserDto;
    headers: {
        /**
         * BasicAuth token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/experience';
};

export type PostApiExperienceErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostApiExperienceResponses = {
    /**
     * Created experience
     */
    201: ExperienceDto;
};

export type PostApiExperienceResponse = PostApiExperienceResponses[keyof PostApiExperienceResponses];

export type PutApiExperienceData = {
    /**
     * Experience
     */
    body: ExperienceDto;
    headers: {
        /**
         * BasicAuth token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/experience';
};

export type PutApiExperienceErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PutApiExperienceResponses = {
    /**
     * Updated experience
     */
    200: ExperienceDto;
};

export type PutApiExperienceResponse = PutApiExperienceResponses[keyof PutApiExperienceResponses];

export type DeleteApiTechnologyData = {
    body?: never;
    headers: {
        /**
         * BasicAuth token
         */
        Authorization: string;
    };
    path: {
        /**
         * Technology id
         */
        id: number;
    };
    query?: never;
    url: '/api/technology';
};

export type DeleteApiTechnologyErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type DeleteApiTechnologyResponses = {
    /**
     * Success message
     */
    200: ResponseDto;
};

export type DeleteApiTechnologyResponse = DeleteApiTechnologyResponses[keyof DeleteApiTechnologyResponses];

export type GetApiTechnologyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/technology';
};

export type GetApiTechnologyErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetApiTechnologyResponses = {
    /**
     * Technologies
     */
    200: Array<TechnologyDto>;
};

export type GetApiTechnologyResponse = GetApiTechnologyResponses[keyof GetApiTechnologyResponses];

export type PostApiTechnologyData = {
    /**
     * Technology
     */
    body: TechnologyDto;
    headers: {
        /**
         * BasicAuth token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/technology';
};

export type PostApiTechnologyErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostApiTechnologyResponses = {
    /**
     * Created technology
     */
    201: TechnologyDto;
};

export type PostApiTechnologyResponse = PostApiTechnologyResponses[keyof PostApiTechnologyResponses];

export type PutApiTechnologyData = {
    /**
     * Technology
     */
    body: TechnologyDto;
    headers: {
        /**
         * BasicAuth token
         */
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/technology';
};

export type PutApiTechnologyErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PutApiTechnologyResponses = {
    /**
     * Updated technology
     */
    200: TechnologyDto;
};

export type PutApiTechnologyResponse = PutApiTechnologyResponses[keyof PutApiTechnologyResponses];

export type GetApiTelemetryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/telemetry';
};

export type GetApiTelemetryErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetApiTelemetryResponses = {
    /**
     * Telemetries
     */
    200: Array<TelemetryDto>;
};

export type GetApiTelemetryResponse = GetApiTelemetryResponses[keyof GetApiTelemetryResponses];

export type PostApiTelemetryData = {
    /**
     * Telemetry
     */
    body: TelemetryDto;
    path?: never;
    query?: never;
    url: '/api/telemetry';
};

export type PostApiTelemetryErrors = {
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type PostApiTelemetryResponses = {
    /**
     * Created telemetry
     */
    201: ExperienceDto;
};

export type PostApiTelemetryResponse = PostApiTelemetryResponses[keyof PostApiTelemetryResponses];

export type ClientOptions = {
    baseUrl: string;
};